### ISSUE TITLE
`to_s': stack level too deep (SystemStackError)

### ISSUE THREAD

**Issue by igorescobar** [bugsnag/bugsnag-ruby#577]
### Description
We are having this error on our bugsnag account every since we installed this gem to integrate with bugsnag. Is this known? The information we have it's not really helpful so I thought about reporting it to see if this is really happening from the gem itself or not.

Btw: This is happening only for our delayed_jobs

### Issue
```
gems/activesupport-6.0.1/lib/active_support/core_ext/numeric/conversions.rb:107:in `to_s': stack level too deep (SystemStackError)
    from gems/bugsnag-6.12.2/lib/bugsnag/cleaner.rb:100:in `filters_match?'
    from gems/bugsnag-6.12.2/lib/bugsnag/cleaner.rb:115:in `filters_match_deeply?'
    from gems/bugsnag-6.12.2/lib/bugsnag/cleaner.rb:33:in `block in traverse_object'
    from gems/bugsnag-6.12.2/lib/bugsnag/cleaner.rb:32:in `each'
    from gems/bugsnag-6.12.2/lib/bugsnag/cleaner.rb:32:in `traverse_object'
    from gems/bugsnag-6.12.2/lib/bugsnag/cleaner.rb:36:in `block in traverse_object'
    from gems/bugsnag-6.12.2/lib/bugsnag/cleaner.rb:32:in `each'
    from gems/bugsnag-6.12.2/lib/bugsnag/cleaner.rb:32:in `traverse_object'
    from gems/bugsnag-6.12.2/lib/bugsnag/cleaner.rb:41:in `block in traverse_object'
    from gems/bugsnag-6.12.2/lib/bugsnag/cleaner.rb:41:in `map'
    from gems/bugsnag-6.12.2/lib/bugsnag/cleaner.rb:41:in `traverse_object'
    from gems/bugsnag-6.12.2/lib/bugsnag/cleaner.rb:36:in `block in traverse_object'
    from gems/bugsnag-6.12.2/lib/bugsnag/cleaner.rb:32:in `each'
    from gems/bugsnag-6.12.2/lib/bugsnag/cleaner.rb:32:in `traverse_object'
    from gems/bugsnag-6.12.2/lib/bugsnag/cleaner.rb:41:in `block in traverse_object'
    from gems/bugsnag-6.12.2/lib/bugsnag/cleaner.rb:41:in `map'
    from gems/bugsnag-6.12.2/lib/bugsnag/cleaner.rb:41:in `traverse_object'
    from gems/bugsnag-6.12.2/lib/bugsnag/cleaner.rb:36:in `block in traverse_object'
    from gems/bugsnag-6.12.2/lib/bugsnag/cleaner.rb:32:in `each'
    from gems/bugsnag-6.12.2/lib/bugsnag/cleaner.rb:32:in `traverse_object'
    from gems/bugsnag-6.12.2/lib/bugsnag/cleaner.rb:41:in `block in traverse_object'
    from gems/bugsnag-6.12.2/lib/bugsnag/cleaner.rb:41:in `map'
    from gems/bugsnag-6.12.2/lib/bugsnag/cleaner.rb:41:in `traverse_object'
    from gems/bugsnag-6.12.2/lib/bugsnag/cleaner.rb:36:in `block in traverse_object'
    from gems/bugsnag-6.12.2/lib/bugsnag/cleaner.rb:32:in `each'
    from gems/bugsnag-6.12.2/lib/bugsnag/cleaner.rb:32:in `traverse_object'
    from gems/bugsnag-6.12.2/lib/bugsnag/cleaner.rb:17:in `clean_object'
    from gems/bugsnag-6.12.2/lib/bugsnag/cleaner.rb:75:in `clean_object_encoding'
    from gems/bugsnag-6.12.2/lib/bugsnag/helpers.rb:21:in `trim_if_needed'
```

### Environment

Library versions:
  * apipie-rails (0.5.16)
  * bugsnag (6.12.2)
  * delayed_job (4.1.8)
  * delayed_job_active_record (4.1.4)
  * delayed_job_recurring (0.3.8)
  * factory_bot_rails (5.0.2)
  * rails (6.0.1)
  * rails-dom-testing (2.0.3)
  * rails-html-sanitizer (1.3.0)
  * request_store (1.4.1)
  * rspec-rails (4.0.0.beta2)
  * rubocop-rails (2.3.2)
  * sprockets-rails (3.2.1)

debug mode or production?: prod

**Comment by igorescobar** [comment]
I just found the reason. We were using bugsnag along with AppSignal (https://appsignal.com/). After disabling this gem the problem stopped. I hope it helps!

**Comment by phillipsam** [comment]
Hi @igorescobar - thanks for the report! This looks like a bug. We will investigate and get back to you.

**Comment by manubo** [comment]
I run into the same issue since version 6.12, although probably not related to AppSignal. The error only happens on production and AppSignal is also running on staging, where the error does not occur.

All fine with version 6.11.1.

**Comment by mattdyoung** [comment]
Fixed in [v6.13.1](https://github.com/bugsnag/bugsnag-ruby/releases/tag/v6.13.1)

**Comment by manubo** [comment]
I am still not able to deploy to production, still failing when running the Rails `db:migrate`-task. This time it seems it is related to AppSignal.

```
bundler/gems/rails-e063befb14ae/activesupport/lib/active_support/tagged_logging.rb:49:in `current_tags': stack level too deep (SystemStackError)
    from bundler/gems/rails-e063befb14ae/activesupport/lib/active_support/tagged_logging.rb:54:in `tags_text'
    from bundler/gems/rails-e063befb14ae/activesupport/lib/active_support/tagged_logging.rb:23:in `call'
    from /home/deploy/.rbenv/versions/2.7.1/lib/ruby/2.7.0/logger.rb:585:in `format_message'
    from /home/deploy/.rbenv/versions/2.7.1/lib/ruby/2.7.0/logger.rb:475:in `add'
    from bundler/gems/rails-e063befb14ae/activesupport/lib/active_support/logger_thread_safe_level.rb:53:in `add'
    from /home/deploy/.rbenv/versions/2.7.1/lib/ruby/2.7.0/logger.rb:528:in `info'
    from gems/bugsnag-6.13.1/lib/bugsnag/configuration.rb:225:in `info'
    from gems/bugsnag-6.13.1/lib/bugsnag.rb:115:in `block in notify'
    from gems/bugsnag-6.13.1/lib/bugsnag/middleware_stack.rb:89:in `block in run'
    from gems/bugsnag-6.13.1/lib/bugsnag/middleware/callbacks.rb:14:in `call'
    from gems/bugsnag-6.13.1/lib/bugsnag/middleware/warden_user.rb:38:in `call'
    from gems/bugsnag-6.13.1/lib/bugsnag/middleware/rails3_request.rb:37:in `call'
    from gems/bugsnag-6.13.1/lib/bugsnag/middleware/rack_request.rb:90:in `call'
    from gems/bugsnag-6.13.1/lib/bugsnag/middleware_stack.rb:94:in `run'
    from gems/bugsnag-6.13.1/lib/bugsnag.rb:91:in `notify'
    from gems/bugsnag-6.13.1/lib/bugsnag/integrations/rake.rb:21:in `rescue in execute'
    from gems/bugsnag-6.13.1/lib/bugsnag/integrations/rake.rb:20:in `execute'
    from gems/appsignal-2.10.6/lib/appsignal/hooks/rake.rb:18:in `execute'
    from gems/bugsnag-6.13.1/lib/bugsnag/integrations/rake.rb:19:in `execute'
    from gems/appsignal-2.10.6/lib/appsignal/hooks/rake.rb:18:in `execute'
    from gems/bugsnag-6.13.1/lib/bugsnag/integrations/rake.rb:19:in `execute'
    from gems/appsignal-2.10.6/lib/appsignal/hooks/rake.rb:18:in `execute'
    from gems/bugsnag-6.13.1/lib/bugsnag/integrations/rake.rb:19:in `execute'
    from gems/appsignal-2.10.6/lib/appsignal/hooks/rake.rb:18:in `execute'
    from gems/bugsnag-6.13.1/lib/bugsnag/integrations/rake.rb:19:in `execute'
    from gems/appsignal-2.10.6/lib/appsignal/hooks/rake.rb:18:in `execute'
    from gems/bugsnag-6.13.1/lib/bugsnag/integrations/rake.rb:19:in `execute'
    from gems/appsignal-2.10.6/lib/appsignal/hooks/rake.rb:18:in `execute'
    from gems/bugsnag-6.13.1/lib/bugsnag/integrations/rake.rb:19:in `execute'
```

**Comment by imjoehaines** [comment]
Hi @manubo, that error seems to be caused by AppSignal using `alias_method` where we're using `Module#prepend` and they aren't compatible with eachother - see https://github.com/bugsnag/bugsnag-ruby/issues/556 and https://github.com/bugsnag/bugsnag-ruby/pull/559 for some background

Unfortunately there's no easy fix for this as if we revert the `Module#prepend` change, then we'll break compatiability with any package that uses `Module#prepend`. We're looking at ways we can fix this but it's a difficult problem to solve

This [blog post by New Relic](https://blog.newrelic.com/engineering/ruby-agent-module-prepend-alias-method-chains/) explains the problem in-depth and has a suggested fix under the heading "What should customers do currently?" - essentially Bugsnag and AppSignal should work together if Bugsnag is loaded after AppSignal. Hopefully this works for you

AppSignal have an open issue for this problem which may be worth keeping an eye on too - https://github.com/appsignal/appsignal-ruby/issues/603

**Comment by manubo** [comment]
@imjoehaines Thanks Joe for sharing that 👍🏼
